{{- include "ffc-helm-library.container-config-map" (list . "ffc-ahwr-sfd-messaging-proxy.config-map") -}}
{{- define "ffc-ahwr-sfd-messaging-proxy.config-map" -}}
data:
  NODE_ENV: {{ .Values.environment | quote }}
  PORT: {{ .Values.container.port | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Chart.Name | quote }}
  TEST_NEW: {{ .Values.environment | quote }}
{{- end -}}
