# Required values to support CI pipeline
environment: development
name: ffc-ahwr-sfd-messaging-proxy
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-sfd-messaging-proxy

labels: {}

aadPodIdentity: true

appInsights:
  connectionString:

# Enable if Managed Identity is required, ensure the clientID and resourceID are set in Platform Configuration
azureIdentity:
  enabled: false
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-ahwr-sfd-messaging-proxy-config-map

containerSecret:
  name: ffc-ahwr-sfd-messaging-proxy-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: default
  restartPolicy: Always
  replicas: 1

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 200Mi
  limitCpu: 200m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
