# Required values to support CI pipeline
environment: production
environmentCode:
name: ffc-ahwr-sfd-messaging-proxy
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-sfd-messaging-proxy

appInsights:
  connectionString:

labels: {}

containerConfigMap: {}

containerSecret: {}

deployment: {}

port: &port 3000

container:
  resourceTier: M
  port: *port

livenessProbe:
  path: /healthz
  port: *port
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: *port
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

# Enable if Managed Identity is required, ensure the clientID and resourceID are set in Platform Configuration
azureIdentity:
  enabled: false
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
